# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Creates an hello world list
#'
#' @return a named list
rcpp_hello_world <- function() {
    .Call(`_FortMyrmidon_rcpp_hello_world`)
}

