language: cpp
branches:
  only:
  - dev/compat
notifications:
  email: false

dist: bionic
addons:
  apt:
    packages:
      - libeigen3-dev
      - qtbase5-dev

before_install:
  - sudo add-apt-repository -y ppa:maarten-fonville/protobuf
  - sudo apt-get -q update
  - sudo apt-get -y install protobuf-compiler libprotobuf-dev
  - ./scripts/install_fort_hermes.sh

script:
  - mkdir -p build
  - cd build
  - cmake  ..
  - make all check
