language: cpp
branches:
  only:
  - master

notifications:
  email: false

dist: bionic
services:
  - xvfb
addons:
  apt:
    packages:
      - libeigen3-dev
      - qtbase5-dev
      - libasio-dev
      - libboost-regex-dev
      - libssl-dev
      - libboost-dev
      - libboost-date-time-dev
      - libboost-filesystem-dev
      - gcovr
      - libopencv-imgcodecs-dev
      - libopencv-imgproc-dev
      - libopencv-dev
      - libxkbcommon-x11-0
      - libgl1-mesa-dev
      - libclang-7-dev

before_install:
  - sudo add-apt-repository -y ppa:maarten-fonville/protobuf
  - sudo apt-get -q update
  - sudo apt-get -y install protobuf-compiler libprotobuf-dev
  - pip install --user cpp-coveralls cldoc

script:
  - mkdir -p build
  - cd build
  - cmake  -DCMAKE_BUILD_TYPE=Debug -DBUILD_DOCS=On ..
#  - make all myrmidon-tests
#  - src/fort/myrmidon/myrmidon-tests
  - make docs-api
  - cd ..
  - mkdir -p docs/dev/api
  - cp -r docs/api/* docs/dev/api/


after_success:
  - coveralls -b build -r . -i 'src/fort/myrmidon' -E '.*UTest.*' --verbose

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: docs/dev/api
  target_branch: gh-pages

cache:
  directories:
    - build/_deps
