language: cpp
branches:
  only:
  - master

notifications:
  email: false

dist: focal
services:
  - xvfb
addons:
  apt:
    packages:
      - libeigen3-dev
      - qtbase5-dev
      - libasio-dev
      - libboost-regex-dev
      - libssl-dev
      - libboost-dev
      - libboost-date-time-dev
      - libboost-filesystem-dev
      - gcovr
      - libopencv-imgcodecs-dev
      - libopencv-imgproc-dev
      - libopencv-dev
      - libxkbcommon-x11-0
      - libgl1-mesa-dev
      - libqt5charts5-dev
      - libyaml-cpp-dev
      - libgoogle-glog-dev
      - libtbb-dev
      - libprotobuf-dev
      - protobuf-compiler
      - python2
      - libclang-10-dev
      - libclang-common-10-dev
      - clang-10


before_install:
  - curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
  - python2 get-pip.py
  - pip3 install --user cpp-coveralls
  - pip2 install --user git+https://github.com/atuleu/cldoc.git@dev/clang-version

script:
  - mkdir -p build
  - cd build
  - cmake -DBUILD_DOCS=On -DENABLE_COVERAGE=On -DBUILD_STUDIO=On ..
  - make all check
  - CLDOC_CLANG_VERSION=10 make docs-api
  - git clone -b gh-pages https://github.com/formicidae-tracker/myrmidon.git gh-pages
  - mkdir -p gh-pages/docs/dev/api
  - cp -r ../docs/api/* gh-pages/docs/dev/api/
  - cd ..

after_success:
  - coveralls -b build -r . -i 'src/fort/myrmidon/priv' -E '.*UTest.*' --verbose

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  local_dir: build/gh-pages/
  target_branch: gh-pages

cache:
  ccache: true
  directories:
    - build/_deps
