language: cpp
branches:
  only:
  - master

notifications:
  email: false

dist: bionic
addons:
  apt:
    packages:
      - libeigen3-dev
      - qtbase5-dev
      - libasio-dev
      - libboost-regex-dev
      - libssl-dev
      - libboost-dev
      - libboost-date-time-dev
      - libboost-filesystem-dev
      - gcovr

before_install:
  - sudo add-apt-repository -y ppa:maarten-fonville/protobuf
  - sudo apt-get -q update
  - sudo apt-get -y install protobuf-compiler libprotobuf-dev
  - pip install --user cpp-coveralls

script:
  - mkdir -p build
  - cd build
  - cmake  -DCMAKE_BUILD_TYPE=Debug ..
  - make all check
  - cd ..

after_success:
  - coveralls -b build -r . -i 'src/myrmidon' -E '.*UTest.*' --verbose

cache:
  directories:
    - build/_deps
