language: cpp
branches:
  only:
  - master

notifications:
  email: false

dist: bionic
services:
  - xvfb
addons:
  apt:
    packages:
      - libeigen3-dev
      - qtbase5-dev
      - libasio-dev
      - libboost-regex-dev
      - libssl-dev
      - libboost-dev
      - libboost-date-time-dev
      - libboost-filesystem-dev
      - gcovr
      - libopencv-imgcodecs-dev
      - libopencv-imgproc-dev
      - libopencv-dev
      - libxkbcommon-x11-0
      - libgl1-mesa-dev
      - libclang-9-dev
      - clang-9

before_install:
  - sudo add-apt-repository -y ppa:maarten-fonville/protobuf
  - sudo apt-get -q update
  - sudo apt-get -y install protobuf-compiler libprotobuf-dev
  - pip install --user cpp-coveralls
  - pip install --user git+https://github.com/atuleu/cldoc.git@dev/clang-version

script:
  - mkdir -p build
  - cd build
  - cmake  -DCMAKE_BUILD_TYPE=Debug -DBUILD_DOCS=On ..
  - make all myrmidon-tests
  - src/fort/myrmidon/myrmidon-tests
  - CLDOC_CLANG_VERSION=9 make docs-api
  - git clone -b gh-pages https://github.com/formicidae-tracker/studio.git gh-pages
  - mkdir -p gh-pages/docs/dev/api
  - cp -r ../docs/api/* gh-pages/docs/dev/api/
  - cd ..

after_success:
  - coveralls -b build -r . -i 'src/fort/myrmidon' -E '.*UTest.*' --verbose

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  local_dir: build/gh-pages/
  target_branch: gh-pages

cache:
  ccache: true
  directories:
    - build/_deps
