r_base:
  - 4.0.*
python:
  - 3.8.*
c_compiler_version:   # [linux]
  - 9.4.*               # [linux]
cxx_compiler_version: # [linux]
  - 9.4.*               # [linux]
opencv:
  - 4.5.1
protobuf:
  - 3.17.2
