{% set name = "fort-myrmidon" %}
{% set version = environ.get('GIT_DESCRIBE_TAG', 'vuntagged')[1:]|string|replace('-','_') %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  number: {{ build_number }}
  string: {{ [build_number, ('h' + PKG_HASH), environ.get('GIT_DESCRIBE_HASH', '')]|join('_') }}


requirements:
  build:
    - cmake =3.16.3
    - make =4.3 [unix]
    - git
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libopencv {{ opencv }}
    - {{ cdt('mesa-libgl-devel') }}  [linux]
    - {{ cdt('mesa-libegl-devel') }} [linux]
    - {{ cdt('mesa-dri-drivers') }}  [linux]
    - {{ cdt('libselinux') }}        [linux]
    - {{ cdt('libxdamage') }}        [linux]
    - {{ cdt('libxfixes') }}         [linux]
    - {{ cdt('libxxf86vm') }}        [linux]
    - libstdcxx-ng {{ c_compiler_version }} [linux]
  host:
    - libstdcxx-ng {{ c_compiler_version }} [linux]
    - eigen =3.4.0
    - tbb-devel =2020.2
    - libprotobuf {{ protobuf }}
    - yaml-cpp =0.6.3
    - asio =1.14.1
    - libopencv {{ opencv }}

outputs:
  - name: libfort-myrmidon
    files:
      - lib/FortMyrmidon
      - lib/FortTags
      - lib/FortHermesCpp
      - lib/FortTime
      - lib/pkgconfig/fort-*.pc
      - lib/libfort-*
      - include/fort
      - include/apriltag
    requirements:
      run:
        - eigen =3.4.0
        - libprotobuf {{ protobuf }}
        - libopencv {{ opencv }}
        - yaml-cpp =0.6.3
        - tbb =2020.2
        - libstdcxx-ng {{ c_compiler_version }} [linux]
    test:
      script: test-libfort-myrmidon.sh
      requires:
        - cmake =3.16.3
        - make =4.3 [unix]
      files:
        - cross-linux.cmake
        - hello-world-myrmidon/main.cpp
        - hello-world-myrmidon/CMakeLists.txt

  - name: r-fort-myrmidon
    script: install-r-fort-myrmidon.sh
    build:
      rpaths:
        - lib/R/lib
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - make
      host:
        - r-base {{ r_base }}
        - r-rcpp
        - r-testthat
        - r-codetools
        - {{ pin_subpackage('libfort-myrmidon', exact=True) }}
        - libprotobuf {{ protobuf }}
        - libopencv {{ opencv }}
        - yaml-cpp =0.6.3
        - eigen =3.4.0
        - libstdcxx-ng {{ c_compiler_version }} [linux]
      run:
        - r-base {{ r_base }}
        - r-rcpp
        - r-codetools
        - {{ pin_subpackage('libfort-myrmidon', exact=True) }}
        - libprotobuf {{ protobuf }}
        - libopencv {{ opencv }}
        - yaml-cpp =0.6.3
        - libstdcxx-ng {{ c_compiler_version }} [linux]
    test:
      files:
        - test-r-fort-myrmidon.r
      commands:
        - Rscript test-r-fort-myrmidon.r

  - name: py-fort-myrmidon
    script: install-py-fort-myrmidon.sh
    requirements:
      build:
        - python {{python}}
        - opencv {{ opencv }}
        - libprotobuf {{ protobuf }}
      host:
        - python {{python}}
        - {{ pin_subpackage('libfort-myrmidon',exact=True) }}
        - pybind11 =2.7.1
        - libprotobuf {{ protobuf }}
        - numpy =1.21.2
        - libstdcxx-ng {{ c_compiler_version }} [linux]
        - opencv {{ opencv }}
        - pandas
        - tqdm
      run:
        - python {{python}}
        - {{ pin_subpackage('libfort-myrmidon',exact=True) }}
        - libprotobuf {{ protobuf }}
        - opencv {{ opencv }}
        - yaml-cpp =0.6.3
        - numpy =1.21.2
        - libstdcxx-ng {{ c_compiler_version }} [linux]
        - pandas
        - tqdm
    test:
      files:
        - test-py-fort-myrmidon.py
      commands:
        - python test-py-fort-myrmidon.py

about:
  home: https://github.com/formicidae-tracker/myrmidon
  license: LGPL-v3
  summary: "FORmicidae Tracker post-processing API and tool"
  description: |
    This module provides fort-myrmidon the FORmicidae Tracker
    post-processing API and FORT Studio, the post-processing GUI
