package:
  name: "fort-myrmidon"
  version: "{{ GIT_DESCRIBE_TAG[1:] }}"

source:
  git_url: ../

build:
  number: 0


requirements:
  build:
    - cmake 3.16.3
    - make [unix]
    - git
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - tbb-devel 2020.2
    - libopencv
    - libprotobuf
    - mesalib
    - yaml-cpp
    - asio


outputs:
  - name: libfort-myrmidon
    files:
      - lib/FortMyrmidon
      - lib/FortTags
      - lib/FortHermesCpp
      - lib/pkgconfig/fort-*.pc
      - lib/libfort-*
      - include/fort
      - include/apriltag
    requirements:
      run:
        - eigen >=3.3.7
        - libprotobuf
        - libopencv
        - yaml-cpp
    test:
      script: test-libfort-myrmidon.sh
      requires:
        - cmake
        - make [unix]
      files:
        - cross-linux.cmake
        - hello-world-myrmidon/main.cpp
        - hello-world-myrmidon/CMakeLists.txt
