package:
  name: "fort-myrmidon"
  version: "{{ GIT_DESCRIBE_TAG[1:] }}"

source:
  git_url: ../

build:
  number: 0


requirements:
  build:
    - cmake =3.16.3
    - make [unix]
    - git
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libopencv
    - {{ cdt('mesa-libgl-devel') }}  [linux]
    - {{ cdt('mesa-libegl-devel') }} [linux]
    - {{ cdt('mesa-dri-drivers') }}  [linux]
    - {{ cdt('libselinux') }}        [linux]
    - {{ cdt('libxdamage') }}        [linux]
    - {{ cdt('libxfixes') }}         [linux]
    - {{ cdt('libxxf86vm') }}        [linux]
  host:
    - tbb-devel <=2020.2
    - libprotobuf
    - yaml-cpp
    - asio
    - glog
    - libopencv

outputs:
  - name: libfort-myrmidon
    files:
      - lib/FortMyrmidon
      - lib/FortTags
      - lib/FortHermesCpp
      - lib/pkgconfig/fort-*.pc
      - lib/libfort-*
      - include/fort
      - include/apriltag
    requirements:
      run:
        - eigen
        - libprotobuf
        - libopencv
        - yaml-cpp
    test:
      script: test-libfort-myrmidon.sh
      requires:
        - cmake =3.16.3
        - make [unix]
      files:
        - cross-linux.cmake
        - hello-world-myrmidon/main.cpp
        - hello-world-myrmidon/CMakeLists.txt

  - name: fort-studio
    files:
      - bin/fort-studio*
    requirements:
      run:
        - glog
        - {{ pin_subpackage('libfort-myrmidon', exact=True) }}
        - libprotobuf
        - libopencv
        - yaml-cpp

    test:
      script: test-fort-studio.sh

  - name: r-fort-myrmidon
    script: install-r-fort-myrmidon.sh
    build:
      rpaths:
        - lib/R/lib
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - make
      host:
        - r-base {{ r_base }}
        - r-rcpp
        - {{ pin_subpackage('libfort-myrmidon', exact=True) }}
        - libprotobuf
        - libopencv
        - yaml-cpp
      run:
        - r-base {{ r_base }}
        - r-rcpp
        - libfort-myrmidon
        - libprotobuf
        - libopencv
        - yaml-cpp
    test:
      files:
        - test-r-fort-myrmidon.r
      commands:
        - Rscript test-r-fort-myrmidon.r

about:
  home: https://github.com/formicidae-tracker/studio
  license: LGPL-v3
  summary: "FORmicidae Tracker post-processing API and tool"
  description: |
    This module provides fort-myrmidon the FORmicidae Tracker
    post-processing API and FORT Studio, the post-processing GUI
