name: fort-studio
version: git
summary:  Graphical User Interface for the FORmicidae Tracker post-processing pipeline
description: |
    fort-studio is a graphical interface that helps set up the
    post-processing of the FORmicidae Tracker tracking data through
    the fort-myrmidon API.

base: core20
confinement: strict

plugs: # plugs for theming, font settings, cursor and to use gtk3 file chooser
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes

apps:
  fort-studio:
    adapter: full
    command: usr/bin/fort-studio
    command-chain:
      - bin/desktop-launch
      - launch-blas-lapack-style
    environment:
      # Use GTK3 cursor theme, icon theme and open/save file dialogs.
      SNAP_DESKTOP_RUNTIME: $SNAP/data-dir/gnome-platform
      GTK_EXE_PREFIX: $SNAP/usr
      QT_QPA_PLATFORMTHEME: gtk3
    plugs:
      - opengl
      - home
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - network
      - network-bind
      - gsettings
      - removable-media

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - ibus-gtk3
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - adwaita-qt
      - xdg-user-dirs
      - fcitx-frontend-qt5


  qt5-gtk-platform:
    plugin: nil
    stage-packages:
      - qt5-gtk-platformtheme

  desktop-settings-packages:
    after: [desktop-qt5]
    plugin: nil
    build-packages:
      - libglib2.0-bin
    stage-packages:
      - gsettings-desktop-schemas
      - ubuntu-settings
    prime:
      - usr/share/glib-2.0/schemas/*

  desktop-settings-build:
    plugin: nil
    after: [ fort-studio, desktop-settings-packages ]
    override-prime: |
      set -eux
      glib-compile-schemas usr/share/glib-2.0/schemas

  launcher:
    plugin: dump
    source: snap/local
    source-type: local

  fort-studio:
    plugin: cmake
    source: .
    source-type: local
    build-packages:
      - make
      - git
      - libeigen3-dev
      - libopencv-dev
      - libprotobuf-dev
      - protobuf-compiler
      - libasio-dev
      - libboost-dev
      - libyaml-cpp-dev
      - libgoogle-glog-dev
      - qtbase5-dev
      - libqt5charts5-dev
    stage-packages:
      - libopencv-videoio4.2
      - libopencv-imgproc4.2
      - libopencv-imgcodecs4.2
      - libqt5charts5
      - libqt5concurrent5
      - libprotobuf17
      - libyaml-cpp0.6
      - libgoogle-glog0v5
      - libglu1-mesa
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DBUILD_STUDIO=On
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
