name: fort-studio
version: git
summary:  Graphical User Interface for the FORmicidae Tracker post-processing pipeline
description: |
    fort-studio is a graphical interface that helps set up the
    post-processing of the FORmicidae Tracker tracking data through
    the fort-myrmidon API.
base: core20
confinement: strict
parts:
  fort-studio:
    plugin: cmake
    source: .
    source-type: local
    build-packages:
      - g++
      - make
      - git
      - libeigen3-dev
      - libopencv-dev
      - libprotobuf-dev
      - protobuf-compiler
      - qtbase5-dev
      - libasio-dev
      - libboost-dev
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    stage:
      - usr/lib/libfort-*
      - usr/bin/fort-studio-*

apps:
  fort-studio:
    command: usr/bin/fort-studio
    environment:
      GST_PLUGIN_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0"
      GST_PLUGIN_SYSTEM_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0"
      GST_PLUGIN_SCANNER: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner"
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack:$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/qt5/libs:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio/"
      QT_PLUGIN_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP_DESKTOP_RUNTIME/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins:$SNAP_DESKTOP_RUNTIME/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"
#      QT_QPA_PLATFORMTHEME: "gtk3"
    plugs:
      - home
      - x11
      - desktop
      - desktop-legacy
      - wayland
      - opengl
