name: Building
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  run-tests-coverage-docs:
    runs-on: ubuntu-20.04
    steps:
        - name: Checkout
          uses: actions/checkout@v2.0.0
        - name: Get all git tags
          run: git fetch --prune --unshallow --tags
        - name: Install dependencies
          run: |
              sudo apt update
              sudo apt install build-essential \
                               git \
                               cmake \
                               libopencv-dev \
                               python3-opencv \
                               libasio-dev \
                               libboost-dev \
                               libgoogle-glog-dev \
                               libyaml-cpp-dev \
                               qtbase5-dev \
                               libqt5charts5-dev \
                               libeigen3-dev \
                               libprotobuf-dev \
                               protobuf-compiler \
                               lcov \
                               doxygen \
                               ccache
              pip install sphinx>=4.2.0 \
                          sphinx_rtd_theme>=1.0.0 \
                          breathe \
                          numpy \
                          pybind11 \
                          pandas
        - name: Uses ccache
          uses: hendrikmuhs/ccache-action@v1
        - name: Configure
          run: |
              export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
              cmake -B ${{github.workspace}}/build \
                    -Dpybind11_DIR=$(pip show pybind11 | grep Location | cut -d " " -f 2)/pybind11/share/cmake/pybind11 \
                    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
                    -DBUILD_STUDIO=On \
                    -DENABLE_COVERAGE=On \
                    -DBUILD_DOCS=On \
                    -DBUILD_PYTHON=On
        - name: Build
          working-directory: ${{github.workspace}}/build
          run: |
              export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
              make all
        - name: Test
          uses: GabrielBB/xvfb-action@v1
          with:
            run: make coverage
            working-directory: ${{github.workspace}}/build
        - name: Sends coverage
          uses: codecov/codecov-action@v2
          id: send-coverage
          with:
            directory: ${{github.workspace}}/build/coverage
        - name: Build documentation
          run: make fort-myrmidon-docs
          working-directory: ${{github.workspace}}/build/
        - name: Uploads documentation
          uses: actions/upload-artifact@v2
          with:
            name: sphinx-documentation
            path: ${{github.workspace}}/build/docs/sphinx

  deploys-documentation:
    runs-on: ubuntu-latest
    needs: run-tests-coverage-docs
    steps:
      - name: Checkout pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Download build documentation
        uses: actions/download-artifact@v2
        with:
          name: sphinx-documentation
          path: _build
      - name: Copy new build
        run: |
          set -x
          rsync -avh --exclude _static _build/ latest --delete
          ln -sf ../_static latest/_static
          rsync -avh _build/_static/ _static
          ./linkVersion.sh
          rm -f _static/_static
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        if: ${{ github.event_name == 'push' }}
        with:
          branch: gh-pages
          folder: .
