name: cibuildwheel
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types: published

jobs:
  build-python-wheels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install build
      - name: Build sdist
        run: python -m build --sdist
        working-directory: bindings/python

      - uses: pypa/cibuildwheel@v3.0.1
        with:
          package-dir: bindings/python/dist/formicidae-tracker-myrmidon-*.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: cib
