name: Documentation
on:
  release:
    types: published
  workflow_dispatch:
    input:
      version:
        description: 'Version to tag'
        required: true

jobs:
  pins-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Release new version
        run: |
          set -x
          RELEASE="${{github.event.inputs.version}}"
          rsync -avh latest/ $RELEASE --delete
          ./linkVersion.sh
        if: ${{ github.event_name == 'workflow_dispatch'}}
      - name: Release new version
        run: |
          set -x
          RELEASE=${GITHUB_REF#"refs/tags/"}
          rsync -avh latest/ $RELEASE --delete
          ./linkVersion.sh
        if: ${{ github.event_name != 'workflow_dispatch'}}
      - name: Deploys
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
