on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types: published


jobs:
  flatpak:
    runs-on: ubuntu-latest
    name: Flatpak
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:kde-6.7
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Fetches all tags
        run: git fetch --prune --unshallow --tags -f
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        name: "Build"
        with:
          bundle: io.github.formicidae_tracker.Studio.flatpak
          manifest-path: misc/flatpak/io.github.formicidae_tracker.Studio.yml
          cache-key: flatpak-builder-${{ github.sha }}
