name: run-tests
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
        - name: Checkout
          uses: actions/checkout@v2.0.0
        - name: Install dependencies
          run: sudo apt install build-essential git cmake libopencv-dev libasio-dev libboost-dev libgoogle-glog-dev libyaml-cpp-dev qtbase5-dev libqt5charts5-dev libeigen3-dev libprotobuf-dev protobuf-compiler gcovr
        - name: Uses ccache
          uses: hendrikmuhs/ccache-action@v1
        - name: Configure
          run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_STUDIO=On -DENABLE_COVERAGE=On
        - name: Build
          working-directory: ${{github.workspace}}/build
          run: make all
        - name: Test
          uses: GabrielBB/xvfb-action@v1
          with:
            run: make check
            working-directory: ${{github.workspace}}/build

  send-coverage:
    runs-on: ubuntu-20.04
    needs: run-tests
    env:
      COVERALLS_REPO_TOKEN : ${{ secrets.github_token }}
    steps:
      - name: Installs coveralls-cpp
        run: pip3 install --user cpp-coveralls
      - name: Sends coverage
        run: coveralls -b ${{github.workspace}}/build -r {{github.workspace}} -i 'src/for/myrmidon/priv' -E '.*UTest.*'
