name: cibuildwheel
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types: published

jobs:
  snap-fort-studio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
