name: Snap
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    release:
      types: published

jobs:
  snap-fort-studio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetches all tags
        run: git fetch --prune --unshallow --tags
      - uses: snapcore/action-build@v1
      - name: Login to snap
        run: |
          echo "${{ secrets.SNAPCRAFT_TOKEN}}" | snapcraft login --with -
      - name: Upload on edge
        if: ${{ github.event_name == 'push' }}
        run: snapcraft upload --release edge fort-studio*.snap
      - name: Upload on beta
        if: ${{ github.event_name == 'release' }}
        run: snapcraft upload --release candidate fort-studio*.snap
