name: Snap
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types: published

jobs:
  snap-fort-studio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetches all tags
        run: git fetch --prune --unshallow --tags -f
      - uses: snapcore/action-build@v1
        id: build
      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.SNAPCRAFT_TOKEN }}
          snap: ${{ steps.build.outputs.snap }}
          release: edge
        if: ${{ github.event_name == 'push' }}
      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.SNAPCRAFT_TOKEN }}
          snap: ${{ steps.build.outputs.snap }}
          release: candidate
        if: ${{ github.event_name == 'release' }}
